### ISSUE TITLE
[1.15.2] Crash Failed to create mod instance

### ISSUE THREAD

**Issue by shortybsd** [shedaniel/LightOverlay-Fabric#25]
Minecraft crashed upon load. 
`Failed to create mod instance. ModID: lightoverlay-forge, class me.shedaniel.lightoverlay.LightOverlay`
Using correct version of dependency (ClothConfig) for Forge.

Forge Version: 31.1.0
LightOverlay Version: 4.1
ClothConfig Version: 2-2.0 for Forge

[Crash Details](https://pastebin.com/7vfgEByA)

**Comment by shedaniel** [comment]
Umm did you try the latest version of all dependencies?

**Comment by shortybsd** [comment]
Yes for only the one dependency for Forge. If you notice on my original post the dependency version is on that post version 2-2.0. I tried LightOverlay 4.2 for 1.15.2 and it is totally broke as well. Same exact error. What forge version have you tested and developed this mod in?

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/76105875-c5a6af00-6010-11ea-824c-d635c78f088d.png)
Failed to reproduce, your crash seems to be related to a method not found, which will probably affect not only light overlay, is light overlay the only mod broken?

**Comment by shortybsd** [comment]
Try loading it on Forge version 31.1.0 (recommended version). You will see that is the issue as your mod only supports the latest version of Forge. Yes, Light overlay is the only other mod broken. I use recommended version of Forge for my mod development environment as well for any Modpacks I make.

**Comment by shedaniel** [comment]
Please, never ever use the recommended version, it is not recommended at all.

**Comment by shedaniel** [comment]
The recommended version only mean "oh yeah we haven't released a recommended for a while, let's do it.", also Light Overlay worked on `1.15.1-30.0.51`, which is a much older version, something is wrong with your end.

**Comment by shedaniel** [comment]
And in your crash report, the line `java.lang.NoSuchMethodError: net.minecraft.client.Minecraft.func_71410_x()Lnet/minecraft/client/Minecraft;` means that the `Minecraft.getInstance()` method is not present on your end, there are two possibilities, one, you are on a development environment, with MCP mappings; two, your mapped Minecraft jar is having some issues.

**Comment by shedaniel** [comment]
As seen on your logs, **you are putting an obf mod jar into the development environment**, I haven't had time to look deep into your crash log before.

You are applying mods wrong probably.

**Comment by shedaniel** [comment]
Try using forge gradle to remap the jar before launching Minecraft with it.

> Light overlay is the only other mod broken

Are you sure? Do you even have other mods except for your own mod in the development environment?

**Comment by shedaniel** [comment]
![image](https://user-images.githubusercontent.com/34910653/76115368-00194780-6023-11ea-91ef-b5fc79097cc8.png)

Picture of running Light Overlay with a much older Forge version.

**Comment by shortybsd** [comment]
Yeah, I have about 5 other mods loaded in dev environment. I design my modpack in another environment but was using a few other mods to test compatibility, was using yours to show my lights :)

**Comment by shedaniel** [comment]
If you don't believe try putting JEI in the mods folder and watch it crash.

https://www.curseforge.com/minecraft/mc-mods/jei/download/2866141

**Comment by shortybsd** [comment]
JEI is one of my 5 others lol, works fine as my crafting table has JEI support and just tested with it. I will update mappings as will make a new test environment for specifically testing with latest version of forge. Pretty sure that will fix it.

**Comment by shedaniel** [comment]
Did you depend on JEI with gradle?

**Comment by shortybsd** [comment]
Absolutely

**Comment by shedaniel** [comment]
Well that's the difference, I didn't set up a maven for Light Overlay because not a lot of people will depend on it, but you still need to add light overlay with gradle.

**Comment by shedaniel** [comment]
If you try adding JEI with mods folder, it would crash.

**Comment by shedaniel** [comment]
I am closing this issue.
