### ISSUE TITLE
Minecraft 1.19.4 crash

### ISSUE THREAD

**Issue by PeterTaylorTX** [shedaniel/LightOverlay-Fabric#165]
When pressing F7 the mod crashed the MC instance with the message
"The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void net.minecraft.core.BlockPos.<init>(double, double, double)'"

Log attached
[crash-2023-03-20_10.54.56-client.txt](https://github.com/shedaniel/LightOverlay/files/11017032/crash-2023-03-20_10.54.56-client.txt)

**Comment by dragonwp** [comment]
mod hasn't been updated since Dec 2022 aka since 1.19.3 so it's not compatible.

**Comment by KensonPlayz** [comment]
Any idea on when this will be fixed?

**Comment by MennoGamed** [comment]
probably dead

**Comment by jasongdove** [comment]
I don't have any Java or Minecraft mod experience, but I have it loading and *kind of* working with 1.19.4 (fabric) at https://github.com/jasongdove/LightOverlay/tree/1.19.4

I referenced this for the migration https://gist.github.com/ChampionAsh5357/163a75e87599d19ee6b4b879821953e8

Unfortunately the overlay doesn't seem to align correctly/behaves strangely when moving the camera. Would be great if someone knew how to fix that.

**Comment by shedaniel** [comment]
Official 1.19.4 version will be done after my HKDSE examination, which will conclude in the second half of May, sorry!

**Comment by PeterTaylorTX** [comment]
No Worries and Good Luck on the Exams

**Comment by Puntherline** [comment]
Awesome news! Good luck with your exams 👍

**Comment by OnlyJugs** [comment]
> Official 1.19.4 version will be done after my HKDSE examination, which will conclude in the second half of May, sorry!

Thanks for at least clarifying if and when you are going to update this. Good luck!
